// Just a simple map of file extensions to MIME types, missing a lot of things, but enough for my needs :D

const ext2mime = {
    // Image
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    gif: 'image/gif',
    webp: 'image/webp',
    ico: 'image/x-icon',
    svg: 'image/svg+xml',
    svgz: 'image/svg+xml',
    bmp: 'image/bmp',
    tiff: 'image/tiff',
    tif: 'image/tiff',
    wbmp: 'image/vnd.wap.wbmp',
    avif: 'image/avif',
    apng: 'image/apng',
    jxl: 'image/jxl',
    heic: 'image/heic',
    heif: 'image/heif',

    // Audio
    mp3: 'audio/mpeg',
    ogg: 'audio/ogg',
    wav: 'audio/wav',
    weba: 'audio/webm',
    mid: 'audio/midi',
    midi: 'audio/midi',
    oga: 'audio/ogg',
    spx: 'audio/ogg',
    opus: 'audio/ogg',
    flac: 'audio/flac',
    m4a: 'audio/mp4',
    aac: 'audio/aac',
    wma: 'audio/x-ms-wma',
    mka: 'audio/x-matroska',

    // Video
    mp4: 'video/mp4',
    webm: 'video/webm',
    ogv: 'video/ogg',
    avi: 'video/x-msvideo',
    wmv: 'video/x-ms-wmv',
    flv: 'video/x-flv',
    mov: 'video/quicktime',
    mkv: 'video/x-matros',
    '3gp': 'video/3gpp',
    '3g2': 'video/3gpp2',
    m4v: 'video/mp4',
    m4p: 'video/mp4',
    m4b: 'video/mp4',
    m4r: 'video/mp4',
    f4v: 'video/mp4',
    f4p: 'video/mp4',
    f4a: 'video/mp4',
    f4b: 'video/mp4',

    // Text
    txt: 'text/plain',
    html: 'text/html',
    htm: 'text/html',
    css: 'text/css',
    js: 'text/javascript',
    md: 'text/markdown',
    markdown: 'text/markdown',
    csv: 'text/csv',
    tsv: 'text/tab-separated-values',
    ics: 'text/calendar',
    vcf: 'text/vcard',

    // Application
    pdf: 'application/pdf',
    doc: 'application/msword',
    xls: 'application/vnd.ms-excel',
    ppt: 'application/vnd.ms-powerpoint',

    // Others
    json: 'application/json',
    xml: 'application/xml',
    zip: 'application/zip',
    rar: 'application/x-rar-compressed',
    '7z': 'application/x-7z-compressed',
    tar: 'application/x-tar',
    gz: 'application/gzip',
    bz2: 'application/x-bzip2',
    xz: 'application/x-xz',
    exe: 'application/x-msdownload',
};

export { ext2mime };
